[workspace]
resolver = "2"
members = [
    "gallivant",
    "gallivant-serial",
    "gallivant-cli",
    "gallivant-errors",
]
default-members = [
    "gallivant",
    "gallivant-serial",
    "gallivant-cli",
]
