[package]
name = "gallivant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.3.0"
chrono = "0.4.31"
chumsky = "0.9.3"
